"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true

[character]
format = "[\\$](green bold) "

[directory]
truncation_length = 100
truncate_to_repo = false

[git_branch]
symbol = ''
format = '\([$symbol$branch(:$remote_branch)]($style)\)'

[git_status]
format = '([$all_status$ahead_behind]($style) )'
conflicted = ''
ahead = ''
behind = ''
diverged = ''
up_to_date = '✓'
untracked = ''
stashed = ''
modified = '🔥'
staged = ''
renamed = ''
deleted = ''

[package]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true
